# Generated by Django 4.1.3 on 2022-11-20 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pills',
            new_name='Pill',
        ),
    ]
