# Generated by Django 4.1.3 on 2022-11-20 22:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_pill_hour_pill_minute_alter_pill_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pill',
            name='hour',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(23), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='pill',
            name='minute',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(59), django.core.validators.MinValueValidator(0)]),
        ),
    ]
